### ISSUE TITLE
dattcore/dattreact: Show balance without receiving new payments

### ISSUE THREAD

**Issue by willy-b** [dattnetwork/datt#98]
Right now if you open/close settings, the balance is inaccurate (reads 0) until a fresh payment comes in , at which point the complete balance across all UTXOs is reflected.

This is because the 'balance' event is not emitted from CoreBitcoin if balances have not changed, and the BoxBitcoin React component is waiting for that event to update state.

**Comment by ryanxcharles** [comment]
This was solved by: https://github.com/dattnetwork/datt/commit/398a1f580d67ab6881519fb827b002ccbfea3524
